version: '3.0'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
  web:
    restart: always
    image: gargron/mastodon:v1.4.3
    env_file: .env.production
    command: ./bin/rails s -p 3000
    depends_on:
      - db
      - redis
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
  streaming:
    restart: always
    image: gargron/mastodon:v1.4.3
    env_file: .env.production
    command: yarn start
    depends_on:
      - db
      - redis
  sidekiq:
    restart: always
    image: gargron/mastodon:v1.4.3
    env_file: .env.production
    command: ./bin/bundle exec sidekiq
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:10080:10080"
    depends_on:
      - web
      - streaming
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./config/nginx:/etc/nginx:ro
      - ./public:/usr/share/nginx/html:ro
